In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data.csv')
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        NaN
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        NaN

In [ ]:
df2 = df.dropna() # drop null rows and here it creates new df

In [4]:
df2

    NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
1  Amith     502     50       70       60.0
2  Rahul     503    170       85       60.0
3   Amar     504     90       50       70.0
4  Rahul     503    170       85       60.0
5   Amar     504     90       50       70.0

In [5]:
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        NaN
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        NaN

In [6]:
df.dropna(inplace=True) # drop null rows and update same df

In [7]:
df

    NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
1  Amith     502     50       70       60.0
2  Rahul     503    170       85       60.0
3   Amar     504     90       50       70.0
4  Rahul     503    170       85       60.0
5   Amar     504     90       50       70.0

In [8]:
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data.csv')
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        NaN
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        NaN

In [ ]:
df2 = df.fillna(0)  # with zero and creates new df

In [11]:
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        NaN
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        NaN

In [12]:
df2

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        0.0
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        0.0

In [13]:
df.fillna(0,inplace=True)  # with zero and update same df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        0.0
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        0.0

In [14]:
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        0.0
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        0.0

In [23]:
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data.csv')
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        NaN
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        NaN

In [25]:
# Replace sepecefic col
df.fillna({'CHEMISTRY':0},inplace=True)
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY
0  Rohith     501     90       80        0.0
1   Amith     502     50       70       60.0
2   Rahul     503    170       85       60.0
3    Amar     504     90       50       70.0
4   Rahul     503    170       85       60.0
5    Amar     504     90       50       70.0
6   James     505     70       50        0.0

In [26]:
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [27]:
mean = df['AGE'].mean()
mean_round = round(mean)
print(mean)
print(mean_round)

16.4
16

In [28]:
# Replace specefic column with mean of that column
df.fillna({'AGE':mean_round},inplace=True)
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60  16.0
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60  16.0
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [35]:
#or another way 
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')

In [36]:
df['AGE'].fillna(round(df['AGE'].mean()),inplace=True)

C:\Users\Mouli\AppData\Local\Temp\ipykernel_15216\1814948034.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['AGE'].fillna(round(df['AGE'].mean()),inplace=True)

0    16.0
1    16.0
2    16.0
3    17.0
4    16.0
5    17.0
6    16.0
Name: AGE, dtype: float64

In [39]:
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [40]:
df['AGE'] = df['AGE'].fillna(round(df['AGE'].mean()))

In [43]:
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60  16.0
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60  16.0
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [44]:
# replace null values with median
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')

In [45]:
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [46]:
median = round(df.AGE.median())
df.fillna({'AGE':median},inplace=True)

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60  16.0
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60  16.0
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [47]:
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60  16.0
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60  16.0
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [48]:
# replace null values with median
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')

In [75]:
median = round(df.AGE.median())
df.AGE = df.AGE.fillna({'AGE':median})
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [54]:
# replace with mode
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')

df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [63]:
#mode = round(df.AGE.mode())
#print(mode)
mode = round(df.AGE.mode()[0])  # why [0] please check above line 
print(mode)
df.fillna({'AGE':mode},inplace=True)

16

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60  16.0
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60  16.0
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [64]:
# replace with mode
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [73]:
#mode = round(df.AGE.mode())
#print(mode)
mode = round(df.AGE.mode()[0])  # why [0] please check above line 
print(mode)
df.AGE  = df['AGE'].fillna({'AGE':mode})
#df.AGE = df.AGE.fillna({'AGE':median})
df

16

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

### handling wrong data . In the above data we see marks as 170(wrong data). Replace wrong data

In [76]:
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [78]:
df.loc[[2,4],'MATHS'] = 70  #corrected 170 as 70 in 2 and 4th rows of maths col
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503     70       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503     70       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [79]:
# marks above 100 replace with 0
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [81]:
for i in df.index:
    if df.loc[i,'MATHS']>100:
        df.loc[i,'MATHS']= 0
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503      0       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503      0       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [85]:
# we can also drop instead replace
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')
for i in df.index:
    if df.loc[i,'MATHS']>100:
        df.drop(i,inplace=True)
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
3    Amar     504     90       50         70  17.0
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

### Removing duplicated data using --->drop_duplicate()

In [ ]:
df = pd.read_csv(r'E:\python-ds-gen-ai-vijay\data\eda\dirty_data2.csv')
df

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
5    Amar     504     90       50         70  17.0
6   James     505     70       50         70  16.0

In [87]:
df.drop_duplicates(inplace=True)
print(df)

     NAME  ROLLNO  MATHS  PHYSICS  CHEMISTRY   AGE
0  Rohith     501     90       80         60  16.0
1   Amith     502     50       70         60   NaN
2   Rahul     503    170       85         60  16.0
3    Amar     504     90       50         70  17.0
4   Rahul     503    170       85         60   NaN
6   James     505     70       50         70  16.0

In [88]:
# Removing unnecessary data (columns)
# dropping the columns which does not have importance--> Roll no and AGE 
df.drop(["ROLLNO","AGE"], axis=1,inplace=True)
print(df)

     NAME  MATHS  PHYSICS  CHEMISTRY
0  Rohith     90       80         60
1   Amith     50       70         60
2   Rahul    170       85         60
3    Amar     90       50         70
4   Rahul    170       85         60
6   James     70       50         70

### Advantages of data cleaning

* Error free data, Data Quality, Accuracy and Efficiency, complete data , maintains data consistency

### Data Preparation :This should be done after data cleansing

* Datasets-->Train set and Test set
* Validation set , is optional
* Train Set: The set which is used to train the model
* Test set: Used for evaluating the model accuracy
* validation set: for more deeper evaluation of the model

### 3 Approaches to prepare data set
* I - Approach: keep 100% data into train set and 20% to 30% of data for test set
* II - Approach keep 70% to 80%