In [1]:
import pandas as pd

In [2]:
sql = pd.read_csv(r"E:\vs-code-prakash\data\dataset_1_202609172220.csv")

In [ ]:
sql
# select * from dataset_1 d ;

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [ ]:
sql.head(10)
# select * from dataset_1 d limit 10;

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
5,No Urgent Place,Friend(s),Sunny,80,6PM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,6
6,No Urgent Place,Friend(s),Sunny,55,2PM,Carry out & Take away,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,7
7,No Urgent Place,Kid(s),Sunny,80,10AM,Restaurant(<20),2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,8
8,No Urgent Place,Kid(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,9
9,No Urgent Place,Kid(s),Sunny,80,10AM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,10

In [ ]:
sql.passanger.unique()
# select distinct passanger from  dataset_1 d ;

<StringArray>
['Alone', 'Friend(s)', 'Kid(s)', 'Partner']
Length: 4, dtype: str

In [ ]:
sql.passanger.nunique() # count

4

In [ ]:
sql[['weather','temperature']]
# select weather, temperature from dataset_1 d ;

      weather  temperature
0       Sunny           55
1       Sunny           80
2       Sunny           80
3       Sunny           80
4       Sunny           80
...       ...          ...
12679   Rainy           55
12680   Rainy           55
12681   Snowy           30
12682   Snowy           30
12683   Sunny           80

[12684 rows x 2 columns]

In [ ]:
sql[sql['destination']=='Home']
# select * from dataset_1 d where d.destination = 'Home';

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
13,Home,Alone,Sunny,55,6PM,Bar,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,1,0,1,14
14,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,15
15,Home,Alone,Sunny,80,6PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,16
35,Home,Alone,Sunny,55,6PM,Bar,1d,Male,21,Single,...,4~8,4~8,less1,1,0,0,1,0,1,36
36,Home,Alone,Sunny,55,6PM,Restaurant(20-50),1d,Male,21,Single,...,4~8,4~8,less1,1,1,0,0,1,0,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12675,Home,Alone,Snowy,30,10PM,Coffee House,2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,0,1,0,12676
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680

In [16]:
#select * from dataset_1 d ORDER by d.coupon ;
sql.sort_values('coupon')

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
11702,Home,Partner,Sunny,30,10PM,Bar,2h,Female,50plus,Married partner,...,4~8,1~3,less1,1,1,1,0,1,0,11703
9930,No Urgent Place,Alone,Snowy,30,2PM,Bar,1d,Female,21,Single,...,gt8,gt8,4~8,1,0,0,0,1,0,9931
10632,Home,Alone,Rainy,55,6PM,Bar,1d,Male,21,Single,...,gt8,less1,less1,1,1,1,0,1,0,10633
7997,No Urgent Place,Friend(s),Rainy,55,10PM,Bar,2h,Male,26,Unmarried partner,...,4~8,never,1~3,1,1,0,0,1,1,7998
11166,Work,Alone,Snowy,30,7AM,Bar,1d,Female,41,Married partner,...,gt8,1~3,less1,1,1,1,0,1,0,11167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,Home,Alone,Sunny,80,6PM,Restaurant(<20),1d,Female,31,Unmarried partner,...,1~3,1~3,less1,1,0,0,1,0,1,10477
5447,Home,Alone,Sunny,80,10PM,Restaurant(<20),2h,Female,50plus,Single,...,less1,less1,never,1,0,0,1,0,0,5448
10478,Home,Alone,Snowy,30,10PM,Restaurant(<20),2h,Female,31,Unmarried partner,...,1~3,1~3,less1,1,1,1,0,1,0,10479
5440,No Urgent Place,Alone,Sunny,80,2PM,Restaurant(<20),2h,Female,50plus,Single,...,less1,less1,never,1,1,0,0,1,0,5441
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1

In [18]:
# select destination as Destination from dataset_1 d ;
sql.rename(columns={'destination':'Destination'}, inplace=True)
sql

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,Home,Partner,Rainy,55,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12680
12680,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,1,12681
12681,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12682
12682,Work,Alone,Snowy,30,7AM,Bar,1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,0,12683
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

* groupby() = Group similar rows together, then perform a calculation on each group.
* will create groups and each group may have one or more records 
* on those records we have to apply aggregation

| Department | Employee | Salary |
| ---------- | -------- | -----: |
| IT         | Mouli    |  50000 |
| IT         | Ravi     |  60000 |
| HR         | Sita     |  40000 |
| HR         | John     |  45000 |
| Sales      | Raj      |  55000 |

df.groupby("Department")

IT
 ├── Mouli   50000
 └── Ravi    60000

HR
 ├── Sita    40000
 └── John    45000

Sales
 └── Raj     55000

* But groupby() alone doesn't normally give you a useful final table. We usually perform an aggregation.

"Okay, I created the groups. What do you want to do with those groups?"

It returns a GroupBy object, not the final displayed result.

df.groupby("Department")["Salary"].mean()

Department

HR       42500

IT       55000

Sales    55000

In [ ]:
#select d.occupation from dataset_1 d group by d.occupation
sql.groupby(sql.occupation)['occupation']

In [27]:
sql.groupby(sql.occupation)['occupation'].unique()

occupation
Architecture & Engineering                                  [Architecture & Engineering]
Arts Design Entertainment Sports & Media      [Arts Design Entertainment Sports & Media]
Building & Grounds Cleaning & Maintenance    [Building & Grounds Cleaning & Maintenance]
Business & Financial                                              [Business & Financial]
Community & Social Services                                [Community & Social Services]
Computer & Mathematical                                        [Computer & Mathematical]
Construction & Extraction                                    [Construction & Extraction]
Education&Training&Library                                  [Education&Training&Library]
Farming Fishing & Forestry                                  [Farming Fishing & Forestry]
Food Preparation & Serving Related                  [Food Preparation & Serving Related]
Healthcare Practitioners & Technical              [Healthcare Practitioners & Technical]
Healthcare Support                                                  [Healthcare Support]
Installation Maintenance & Repair                    [Installation Maintenance & Repair]
Legal                                                                            [Legal]
Life Physical Social Science                              [Life Physical Social Science]
Management                                                                  [Management]
Office & Administrative Support                        [Office & Administrative Support]
Personal Care & Service                                        [Personal Care & Service]
Production Occupations                                          [Production Occupations]
Protective Service                                                  [Protective Service]
Retired                                                                        [Retired]
Sales & Related                                                        [Sales & Related]
Student                                                                        [Student]
Transportation & Material Moving                      [Transportation & Material Moving]
Unemployed                                                                  [Unemployed]
Name: occupation, dtype: object

In [25]:
sql.groupby(sql.occupation)['occupation'].nunique()

occupation
Architecture & Engineering                   1
Arts Design Entertainment Sports & Media     1
Building & Grounds Cleaning & Maintenance    1
Business & Financial                         1
Community & Social Services                  1
Computer & Mathematical                      1
Construction & Extraction                    1
Education&Training&Library                   1
Farming Fishing & Forestry                   1
Food Preparation & Serving Related           1
Healthcare Practitioners & Technical         1
Healthcare Support                           1
Installation Maintenance & Repair            1
Legal                                        1
Life Physical Social Science                 1
Management                                   1
Office & Administrative Support              1
Personal Care & Service                      1
Production Occupations                       1
Protective Service                           1
Retired                                      1
Sales & Related                              1
Student                                      1
Transportation & Material Moving             1
Unemployed                                   1
Name: occupation, dtype: int64

In [26]:
sql.groupby(sql.occupation)['occupation'].size()

occupation
Architecture & Engineering                    175
Arts Design Entertainment Sports & Media      629
Building & Grounds Cleaning & Maintenance      44
Business & Financial                          544
Community & Social Services                   241
Computer & Mathematical                      1408
Construction & Extraction                     154
Education&Training&Library                    943
Farming Fishing & Forestry                     43
Food Preparation & Serving Related            298
Healthcare Practitioners & Technical          244
Healthcare Support                            242
Installation Maintenance & Repair             133
Legal                                         219
Life Physical Social Science                  170
Management                                    838
Office & Administrative Support               639
Personal Care & Service                       175
Production Occupations                        110
Protective Service                            175
Retired                                       495
Sales & Related                              1093
Student                                      1584
Transportation & Material Moving              218
Unemployed                                   1870
Name: occupation, dtype: int64

In [28]:
sql.groupby(sql.occupation)['occupation'].size().reset_index(name="count")

                                   occupation  count
0                  Architecture & Engineering    175
1    Arts Design Entertainment Sports & Media    629
2   Building & Grounds Cleaning & Maintenance     44
3                        Business & Financial    544
4                 Community & Social Services    241
5                     Computer & Mathematical   1408
6                   Construction & Extraction    154
7                  Education&Training&Library    943
8                  Farming Fishing & Forestry     43
9          Food Preparation & Serving Related    298
10       Healthcare Practitioners & Technical    244
11                         Healthcare Support    242
12          Installation Maintenance & Repair    133
13                                      Legal    219
14               Life Physical Social Science    170
15                                 Management    838
16            Office & Administrative Support    639
17                    Personal Care & Service    175
18                     Production Occupations    110
19                         Protective Service    175
20                                    Retired    495
21                            Sales & Related   1093
22                                    Student   1584
23           Transportation & Material Moving    218
24                                 Unemployed   1870

* dataset_1.groupby("occupation").size()   returns pandas series

Output:

occupation

Doctor           2

Engineer         3

Teacher          1

dtype: int64


Why is it a Series?

Because it has:

Index → occupation

Values → 2, 3, 1

verify :

result = dataset_1.groupby("occupation").size()

print(type(result))


Series
  ↓
Index        Values
--------------------
Doctor   →      2

Engineer →      3

Teacher  →      1

result.reset_index(name="count")

converts that Series → DataFrame:

DataFrame
---------------------

occupation | count

Doctor     | 2

Engineer   | 3

Teacher    | 1

groupby()
   ↓
Grouped object
   ↓
size()
   ↓
Series
   ↓
reset_index()
   ↓
DataFrame

In [ ]:
# select weather, avg(temperature) as avg_temp from dataset_1 group by weather;
# in pandas we do not have avg() function instead to achieve same we use mean()
sql.groupby("weather")['temperature'].mean().to_frame('avg_temp').reset_index()

  weather   avg_temp
0   Rainy  55.000000
1   Snowy  30.000000
2   Sunny  68.946271

In [33]:
# or we can do same for above output because sql.groupby("weather")['temperature'].mean() gives series and whenever we have 
# series in hand better to use below 
sql.groupby("weather")['temperature'].mean().reset_index(name='avg_temp')

  weather   avg_temp
0   Rainy  55.000000
1   Snowy  30.000000
2   Sunny  68.946271

* select weather, COUNT (weather) from dataset_1 group by weather;
* This counts non-NULL values in the weather column for each weather group,including duplicates.

* select weather ,count(temperature) as count_temp from dataset_1 d group by weather;
* count non-NULL temperature values, including duplicates.

* select weather , count(distinct temperature) as dis_count_temp from dataset_1 d  GROUP by weather;
* Ignore NULL,Remove duplicates and Count the remaining values

In [35]:
# select weather ,count(temperature) as count_temp from dataset_1 d group by weather;
#sql.groupby('weather')['temperature'].count().reset_index(name='temp_count')
#below also same
sql.groupby('weather')['temperature'].count().to_frame('temp_count').reset_index()

  weather  temp_count
0   Rainy        1210
1   Snowy        1405
2   Sunny       10069

* size()  → counts rows
* count() → counts non-NULL values

* What are the unique values?"-->unique() → give me the actual unique values

* How many unique values are there? --> nunique() → count unique values

* nunique() doesn't count NaN.

| Pandas      | SQL equivalent               | Meaning                         |
| ----------- | ---------------------------- | ------------------------------- |
| `size()`    | `COUNT(*)`                   | Count rows                      |
| `count()`   | `COUNT(column)`              | Count non-null values           |
| `nunique()` | `COUNT(DISTINCT column)`     | Count unique values             |
| `unique()`  | No direct `COUNT` equivalent | Return the actual unique values |

* size = rows, count = non-null, unique = values, nunique = number of unique value

In [ ]:
# select weather , count(distinct temperature) as dis_count_temp from dataset_1 d  GROUP by weather;
sql.groupby('weather')['temperature'].nunique().reset_index(name='dis_count_temp')
#sql.groupby('weather')['temperature'].nunique().to_frame('dis_count_temp').reset_index()

  weather  dis_count_temp
0   Rainy               1
1   Snowy               1
2   Sunny               3

In [38]:
# select weather , sum(temperature) as sum_temp from dataset_1 d GROUP by weather;
#sql.groupby('weather')['temperature'].sum().reset_index(name='sum_temp')
sql.groupby('weather')['temperature'].sum().to_frame('sum_temp').reset_index()

  weather  sum_temp
0   Rainy     66550
1   Snowy     42150
2   Sunny    694220

In [40]:
# select weather, min(temperature) as min_temp from dataset_1 d  GROUP by weather;
#sql.groupby('weather')['temperature'].min().reset_index(name='min')
sql.groupby('weather')['temperature'].min().to_frame('min').reset_index()

  weather  min
0   Rainy   55
1   Snowy   30
2   Sunny   30

In [42]:
# select weather , max(temperature) as max_temp from dataset_1 d  GROUP  by weather;
#sql.groupby('weather')['temperature'].max().reset_index(name='max_temp')
sql.groupby('weather')['temperature'].max().to_frame('max_temp').reset_index()

  weather  max_temp
0   Rainy        55
1   Snowy        30
2   Sunny        80

In [44]:
# select d.occupation  from dataset_1 d group by d.occupation having d.occupation = 'Student';
sql.groupby('occupation').filter(lambda x:x['occupation'].iloc[0]=='Student')['occupation']

44       Student
45       Student
46       Student
47       Student
48       Student
          ...
12585    Student
12586    Student
12587    Student
12588    Student
12589    Student
Name: occupation, Length: 1584, dtype: str

In [ ]:
sql.groupby('occupation').filter(lambda x:x['occupation'].iloc[0]=='Student')['occupation'].drop_duplicates()
# keeps first and removes all other duplicates

44    Student
Name: occupation, dtype: str

In [48]:
sql.groupby('occupation').filter(lambda x:x['occupation'].iloc[0]=='Student').groupby('occupation').size()

occupation
Student    1584
dtype: int64

In [ ]:
sql[sql['occupation']=='Student']

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
44,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Male,46,Single,...,1~3,1~3,never,1,0,0,0,1,1,45
45,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Male,46,Single,...,1~3,1~3,never,1,0,0,0,1,1,46
46,No Urgent Place,Friend(s),Sunny,80,10AM,Bar,1d,Male,46,Single,...,1~3,1~3,never,1,0,0,0,1,0,47
47,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Male,46,Single,...,1~3,1~3,never,1,1,0,0,1,1,48
48,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Male,46,Single,...,1~3,1~3,never,1,0,0,0,1,1,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12585,Work,Alone,Rainy,55,7AM,Carry out & Take away,1d,Male,21,Single,...,1~3,1~3,less1,1,0,0,0,1,0,12586
12586,Work,Alone,Snowy,30,7AM,Coffee House,1d,Male,21,Single,...,1~3,1~3,less1,1,0,0,1,0,0,12587
12587,Work,Alone,Snowy,30,7AM,Restaurant(<20),1d,Male,21,Single,...,1~3,1~3,less1,1,1,0,0,1,0,12588
12588,Work,Alone,Snowy,30,7AM,Bar,1d,Male,21,Single,...,1~3,1~3,less1,1,1,1,0,1,0,12589
12589,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,21,Single,...,1~3,1~3,less1,1,0,0,1,0,0,12590

In [52]:
sql[sql['occupation']=='Student'].head(2)

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
44,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Male,46,Single,...,1~3,1~3,never,1,0,0,0,1,1,45
45,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Male,46,Single,...,1~3,1~3,never,1,0,0,0,1,1,46

In [55]:
sql.loc[sql['occupation']=='Student','occupation']

44       Student
45       Student
46       Student
47       Student
48       Student
          ...
12585    Student
12586    Student
12587    Student
12588    Student
12589    Student
Name: occupation, Length: 1584, dtype: str

In [ ]:
sql.loc[sql['occupation']=='Student','occupation'].drop_duplicates()
# above is same as below 
# sql.groupby('occupation').filter(lambda x:x['occupation'].iloc[0]=='Student')['occupation'].drop_duplicates()

44    Student
Name: occupation, dtype: str

In [57]:
sql_union = pd.read_csv(r"E:\vs-code-prakash\data\table_to_union_202609191348.csv")

In [58]:
sql_union

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,UNION,UNION,UNION,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1

In [75]:
pd.concat([sql,sql_union]).head(2)

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count,destination
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,4~8,1~3,1,0,0,0,1,1,1,NaN
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,4~8,1~3,1,0,0,0,1,0,2,NaN

In [80]:
print(sql.shape)

(12684, 27)

In [81]:
print(sql_union.shape)

(1, 27)

In [78]:
print(pd.concat([sql,sql_union]).shape)

(12685, 28)

In [71]:
# select distinct destination from (
# select * from dataset_1 d union select * from table_to_union ttu)
pd.concat([sql,sql_union])['Destination']

0        No Urgent Place
1        No Urgent Place
2        No Urgent Place
3        No Urgent Place
4        No Urgent Place
              ...
12680               Work
12681               Work
12682               Work
12683               Work
0                    NaN
Name: Destination, Length: 12685, dtype: str

In [69]:
sql['Destination'].head(5)

0    No Urgent Place
1    No Urgent Place
2    No Urgent Place
3    No Urgent Place
4    No Urgent Place
Name: Destination, dtype: str

In [70]:
#pd.concat([sql,sql_union])['destination'].drop_duplicates()
pd.concat([sql, sql_union]).drop_duplicates()['Destination'].drop_duplicates()

0     No Urgent Place
13               Home
16               Work
0                 NaN
Name: Destination, dtype: str

In [72]:
sql_join = pd.read_csv(r"E:\vs-code-prakash\data\table_to_join_202609191410.csv")

In [73]:
sql_join.head()

   time part_of_day
0   2PM   Afternoon
1  10AM     Morning
2   6PM     Evening
3   7AM     Morning
4  10PM       Night

In [82]:
sql.shape, sql_join.shape

((12684, 27), (5, 2))

In [ ]:
# select d.destination, d.time, ttj.part_of_day  from dataset_1 d inner join table_to_join ttj  on 
# d.time  = ttj.time; 

pd.merge(sql,sql_join[['time','part_of_day']],on='time',how='inner')[['Destination','time','part_of_day']]

           Destination  time part_of_day
0      No Urgent Place   2PM   Afternoon
1      No Urgent Place  10AM     Morning
2      No Urgent Place  10AM     Morning
3      No Urgent Place   2PM   Afternoon
4      No Urgent Place   2PM   Afternoon
...                ...   ...         ...
12679             Home   6PM     Evening
12680             Work   7AM     Morning
12681             Work   7AM     Morning
12682             Work   7AM     Morning
12683             Work   7AM     Morning

[12684 rows x 3 columns]

In [86]:
# select destination, passanger from (
# select * from dataset_1 d  where d.passanger='Alone')
sql[sql['passanger']=='Alone'][['Destination','passanger']]

           Destination passanger
0      No Urgent Place     Alone
13                Home     Alone
14                Home     Alone
15                Home     Alone
16                Work     Alone
...                ...       ...
12676             Home     Alone
12680             Work     Alone
12681             Work     Alone
12682             Work     Alone
12683             Work     Alone

[7305 rows x 2 columns]

In [88]:
# select * from dataset_1 d where d.weather  like 'Sun%';
sql[sql['weather'].str.startswith('Sun')]

,Destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y,row_count
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,0,0,0,1,0,2
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,1,3
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,4
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,NaN,4~8,1~3,1,1,0,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12673,Home,Alone,Sunny,30,6PM,Carry out & Take away,1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,0,1,0,12674
12676,Home,Alone,Sunny,80,6PM,Restaurant(20-50),1d,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,1,12677
12677,Home,Partner,Sunny,30,6PM,Restaurant(<20),1d,Male,26,Single,...,1~3,4~8,1~3,1,1,1,0,1,1,12678
12678,Home,Partner,Sunny,30,10PM,Restaurant(<20),2h,Male,26,Single,...,1~3,4~8,1~3,1,1,0,1,0,0,12679
12683,Work,Alone,Sunny,80,7AM,Restaurant(20-50),2h,Male,26,Single,...,1~3,4~8,1~3,1,0,0,1,0,0,12684

In [89]:
# select distinct temperature from dataset_1 d where d.temperature between 25 and 75;
sql[(sql['temperature']>=25 ) & (sql['temperature']<=75)]['temperature'].unique()

array([55, 30])

In [90]:
# select occupation from dataset_1 d where d.occupation in ('Sales & Related','Management');
sql[sql['occupation'].isin(['Sales & Related', 'Management'])][['occupation']]

            occupation
193    Sales & Related
194    Sales & Related
195    Sales & Related
196    Sales & Related
197    Sales & Related
...                ...
12679  Sales & Related
12680  Sales & Related
12681  Sales & Related
12682  Sales & Related
12683  Sales & Related

[1931 rows x 1 columns]